version: '3.7'

services:
    mysql:
        container_name: ms-register_mysql
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - "3306:3306"
